services:
  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - tusecre_net

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - tusecre_net
    depends_on:
      - app

networks:
  tusecre_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
