version: '3.8'

services:
  lasecre-bot:
    build: .
    container_name: lasecre_bot
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: lasecre_redis
    restart: always
    volumes:
      - ./redis-data:/data
